[project]
name = "app"  # <-- Указываем имя пакета, совпадающее с папкой
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "authlib>=1.8.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "itsdangerous>=2.2.0",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
]

[tool.ruff.lint]
ignore = [
    "RUF012",
    "B008",
]

[project.scripts]
main = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = []
